# In normal usage, you shouldn't need to install any gems as this is done on
# the guest VM. For development/testing (and Travis) it may be useful to install
# the various gems.
source 'https://rubygems.org'

gem 'librarian-puppet'

group :test do
  gem 'rake'

  puppetversion = ENV['PUPPET_VERSION'] || ['>= 3.4.0', '< 4.0.0']
  gem 'puppet', puppetversion

  gem 'puppet-catalog-test'
  gem 'puppet-lint'
  gem 'puppet-syntax'
end
