# In normal usage, you shouldn't need to install any gems as this is done on
# the guest VM. For development/testing (and Travis) it may be useful to install
# the various gems.
source 'https://rubygems.org'

gem 'librarian-puppet', '>=2.2.3'
gem 'inifile'  # Required by camptocamp-openssl module after the first run.

group :test do
  gem 'rake', '<11.0.0'  # See https://github.com/invadersmustdie/puppet-catalog-test/pull/29

  puppet_version = case ENV['PUPPET_VERSION'] || '4'
                   when '3.4'; '3.4.3'
                   when '3.8'; '~>3.8.0'
                   when '4'; '~>4.3.0'
                   end
  gem 'puppet', puppet_version

  gem 'puppet-catalog-test'
  gem 'puppet-lint'
  gem 'puppet-syntax'
end
