forge "https://forgeapi.puppetlabs.com"

mod 'praekeltfoundation/seed_stack',
 :git => 'https://github.com/praekeltfoundation/puppet-seed_stack',
 :ref => 'develop'

# 3rd party modules
mod 'camptocamp/openssl', '>= 1.5.0'
