moduledir 'upstream_modules'

# Basic modules
mod 'puppetlabs/apt', '2.2.1'
mod 'puppetlabs/concat', '1.2.5'
mod 'stahnma/epel', '1.2.2'
mod 'nanliu/staging', '1.0.3'
mod 'puppetlabs/stdlib', '4.10.0'
mod 'richardc/datacat', '0.6.2'

# 3rd party modules
mod 'camptocamp/openssl', '1.5.1'
mod 'deric/mesos', '0.6.4'
mod 'garethr/docker', '4.1.1'
mod 'gdhbashton/consul_template', '0.2.4'
mod 'KyleAnderson/consul', '1.0.4'
mod 'stankevich/python', '1.10.0'
mod 'deric/zookeeper', '0.4.1'
