require 'puppet-catalog-test'
require 'puppet-lint/tasks/puppet-lint'
require 'puppet-syntax/tasks/puppet-syntax'

envdir = File.join("environments", "seed_stack")

exclude_paths = ["vendor/**/*", "modules/**/*"]

PuppetSyntax.fail_on_deprecation_notices = false
PuppetSyntax.exclude_paths = exclude_paths
Rake::Task['syntax:hiera'].clear # Not currently using Hiera

Rake::Task[:lint].clear
PuppetLint::RakeTask.new(:lint) do |config|
  config.fail_on_warnings = true
  config.ignore_paths = exclude_paths
end

desc "Install modules using librarian-puppet"
task :module_install do
  sh "librarian-puppet install --path=#{envdir}/modules"
end

PuppetCatalogTest::RakeTask.new(:catalog) do |t|
  # Both the syntax and catalog initialize Puppet with config. Puppet doesn't
  # like config being set twice. This clears the config if it's set.
  Puppet.settings.send(:clear_everything_for_tests)

  t.module_paths = [File.join(envdir, "modules")]
  t.manifest_path = File.join(envdir, "manifests", "site.pp")
  t.facts = {
    "osfamily" => "Debian",
    "ipaddress_lo" => "127.0.0.1",
    "ipaddress_eth0" => "10.2.3.4",
    "architecture" => "amd64",
    "operatingsystem" => "Ubuntu",
    "operatingsystemrelease" => "14.04",
    "lsbdistid" => "Ubuntu",
    "lsbdistrelease" => "14.04",
    "lsbdistcodename" => "trusty",
    "concat_basedir" => "/tmp/puppetconcat",
  }
end

task :default => [
  :syntax,
  :lint,
  :module_install,
  :catalog,
]
